#!/bin/bash
#SBATCH -J exp_data_dummy
#SBATCH --partition=serial          # Queue (partition) name
#SBATCH --nodes=1               # the number of nodes
#SBATCH --ntasks-per-node=28
#SBATCH -t 24:00:00           # Run time (hh:mm:ss)   walltime for each node separately
#SBATCH --mail-user=liyanage.5@osu.edu
#SBATCH --mail-type=BEGIN,END      # Send email at begin and end of job
#SBATCH -A pas0254      # Allocation name
#COMMANDS TO RUN
#prepare environment
source ~/.bashrc
source set_variable.sh
#cd to working dir
#cd /users/PAS0254/dananjaya/JETSCAPE-SIMS/JETSCAPE-COMP/sims_scripts/submit
cd /users/PAS0254/dananjaya/VAH_SURMISE/emulation
echo "in cwd"
pwd
#prepare the libraries
echo "preparing libraries"
module load python/3.6-conda5.2
#conda activate parton_loss_owens
#conda activate random_field
source activate parton_loss_owens
job=$PBS_JOBID
echo "job : "
echo $job
echo "tmp dir"
echo ${TMPDIR}

n_cores=28
let max_cores=$n_cores-1
n_events_all=5000
n_events_per_core=1
echo "number of cores used : "
echo ${n_cores}
##for best scaling, set nevents 
python3 updated_benchmark_cal_surmise_dan_PCSK_PTMC.py
#wait until all processes are done
wait
echo "All events have finished. Goodbye!"
